In [ ]:
import numpy as np
array1 = np.array([[1,2],
                   [3,4]])
print("1. 2*2 numpy array:\n", array1)

1. 2*2 numpy array:
 [[1 2]
 [3 4]]


In [ ]:
array2 = np.random.rand(3,4)
print("\n2. Random numpy array (3*4):\n", array2)


2. Random numpy array (3*4):
 [[0.55295399 0.23521075 0.25752516 0.47273731]
 [0.02040821 0.87528348 0.20488243 0.7224673 ]
 [0.84593364 0.34067115 0.30936013 0.59206239]]


In [ ]:
ones_array = np.ones((3,3))
zeroes_array = np.zeros((3,3))
print("\n3. Array of ones:\n", ones_array)
print("Array of zeroes:\n", zeroes_array)


3. Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array of zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
array3 = np.random.rand(6,3)
print("\n4. Random array (6*3):\n", array3)
print("Transposed array (3*6):\n", array3.transpose)


4. Random array (6*3):
 [[0.16343011 0.71899223 0.03224963]
 [0.03747823 0.5003005  0.49164605]
 [0.95517955 0.24615625 0.48359729]
 [0.7896457  0.27567684 0.03627737]
 [0.82171808 0.26391184 0.314984  ]
 [0.45427544 0.75925278 0.60781763]]
Transposed array (3*6):
 <built-in method transpose of numpy.ndarray object at 0x7e0b8ec6ac10>


In [ ]:
n, p, m = 2, 3, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)

print("\n5. Matrix A (2*3):\n", A)
print("Matrix B (3*4):\n", B)
print("Dot product (2*4):\n", dot_product)


5. Matrix A (2*3):
 [[0.36823226 0.73847336 0.58317696]
 [0.52865621 0.3156357  0.78519855]]
Matrix B (3*4):
 [[0.1862343  0.31962907 0.26675525 0.49645782]
 [0.17331917 0.54538879 0.88329208 0.6686142 ]
 [0.95353995 0.28044268 0.61649596 0.14559931]]
Dot product (2*4):
 [[0.75265159 0.68400053 1.11004179 0.76147572]
 [0.90187782 0.56132125 0.90389206 0.58781838]]
